// <auto-generated />
namespace TestingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddJsonIgnoreinquesttoansw : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddJsonIgnoreinquesttoansw));
        
        string IMigrationMetadata.Id
        {
            get { return "201911061046399_Add JsonIgnore in quest to answ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
